# Generated by Django 4.2.7 on 2023-12-24 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seller', '0003_alter_goods_good_image_alter_goods_good_price_and_more'),
        ('buyer', '0002_remove_buyerinfo_location_buyerinfo_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('已通过', '已通过'), ('未通过', '未通过')], default='未处理', max_length=10, verbose_name='订单状态')),
                ('date', models.DateTimeField()),
                ('quantity', models.PositiveIntegerField(verbose_name='数目')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer.buyerinfo')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.goods')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=200)),
                ('create_date', models.DateTimeField()),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.goods')),
                ('user', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='buyer.buyerinfo')),
            ],
        ),
    ]
