# Generated by Django 4.2.7 on 2023-12-24 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=15)),
                ('buyer_image', models.ImageField(default='/user/4357443aa53522b.jpg', upload_to='user', verbose_name='用户头像')),
                ('password', models.CharField(max_length=11)),
                ('location', models.CharField(max_length=20)),
            ],
        ),
    ]
