# Generated by Django 4.2.7 on 2023-12-24 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyerinfo',
            name='location',
        ),
        migrations.AddField(
            model_name='buyerinfo',
            name='email',
            field=models.CharField(default='666@qq.com', max_length=25),
        ),
    ]
