# Generated by Django 4.2.7 on 2023-12-17 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SellerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=15)),
                ('seller_image', models.ImageField(default='4357443aa53522b.jpg', upload_to='media', verbose_name='用户头像')),
                ('password', models.CharField(max_length=11)),
            ],
        ),
    ]
